"""修复了product表缺少外键的错误

Revision ID: 188487beb12e
Revises: dff100ffa7e0
Create Date: 2024-07-01 14:55:00.231319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188487beb12e'
down_revision: Union[str, None] = 'dff100ffa7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('store_id', sa.Integer(), nullable=False, comment='店铺ID'))
    op.create_foreign_key(None, 'product', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'store_id')
    # ### end Alembic commands ###
