"""User表增加了is_active和is_superuser字段

Revision ID: c67e5799c040
Revises: 188487beb12e
Create Date: 2024-08-28 14:14:22.646148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c67e5799c040'
down_revision: Union[str, None] = '188487beb12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pest', ['name'])
    op.add_column('user',
                  sa.Column('is_active_', sa.Boolean(create_constraint=True, name='is_active_check', ),
                            nullable=False, comment='是否激活'))
    op.add_column('user', sa.Column('is_superuser_', sa.Boolean(create_constraint=True, name='is_superuser_check'),
                                    nullable=False, comment='是否为超级用户'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser_')
    op.drop_column('user', 'is_active_')
    op.drop_constraint(None, 'pest', type_='unique')
    # ### end Alembic commands ###
