"""调整了UserOrm.password的字符串最大长度为64

Revision ID: d0530f9b2fc5
Revises: 
Create Date: 2024-06-12 19:36:30.712983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0530f9b2fc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    op.drop_index('name', table_name='pest')
    op.drop_table('pest')
    op.drop_index('ix_disease_name', table_name='disease')
    op.drop_table('disease')
    op.drop_table('user')
    op.drop_table('plant_disease')
    op.drop_table('plant_pest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_pest',
    sa.Column('plant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pest_id'], ['pest.id'], name='plant_pest_ibfk_2'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='plant_pest_ibfk_1'),
    sa.PrimaryKeyConstraint('plant_id', 'pest_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plant_disease',
    sa.Column('plant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disease_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], name='plant_disease_ibfk_2'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='plant_disease_ibfk_1'),
    sa.PrimaryKeyConstraint('plant_id', 'disease_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False, comment='用户名'),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False, comment='密码'),
    sa.Column('tel', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11), nullable=True, comment='手机号'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True, comment='邮箱'),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True, comment='头像'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('disease',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=24), nullable=False, comment='病害名称'),
    sa.Column('impact', mysql.TINYINT(), autoincrement=False, nullable=False, comment='影响程度 1高 2中 3低'),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False, comment='病害描述'),
    sa.Column('symptom', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False, comment='发病特征'),
    sa.Column('cause', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False, comment='病害主因'),
    sa.Column('preventive_measure', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False, comment='防治手段'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储玉米的相应病害',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='存储玉米的相应病害',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_disease_name', 'disease', ['name'], unique=True)
    op.create_table('pest',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=24), nullable=False, comment='虫害种类名称'),
    sa.Column('impact', mysql.TINYINT(), autoincrement=False, nullable=False, comment='影响程度 1高 2中 3低'),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False, comment='虫害描述'),
    sa.Column('preventive_measures', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False, comment='防治手段'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储玉米相关虫害',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='存储玉米相关虫害',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'pest', ['name'], unique=True)
    op.create_table('plant',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=24), nullable=False, comment='植物名称'),
    sa.Column('planting_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False, comment='种植地点'),
    sa.Column('media_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True, comment='媒体资源地址'),
    sa.Column('health', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='植物健康分级 1健康 2轻微病害 3严重病害'),
    sa.Column('growth', mysql.TINYINT(), autoincrement=False, nullable=False, comment='植物生长情况 1茂盛 2一般 3枯萎'),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False, comment='植物的描述信息'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plant_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储用户上传的信息',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='存储用户上传的信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
