"""新增商品表,分类表,店铺表

Revision ID: dff100ffa7e0
Revises: 
Create Date: 2024-06-28 21:16:29.920345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff100ffa7e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='商品分类名称'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='店铺名称'),
    sa.Column('logo_img', sa.String(length=32), nullable=False, comment='logo图片地址'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='商品名称'),
    sa.Column('price', sa.Numeric(), nullable=False, comment='商品单价'),
    sa.Column('stock_quantity', sa.Integer(), nullable=False, comment='库存数量'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='类别ID'),
    sa.Column('brand', sa.String(length=64), nullable=True, comment='品牌'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态'),
    sa.Column('image_url', sa.String(length=2048), nullable=True, comment='图片URL,格式为:xxx.jpg,dfg.png,apple.jpg'),
    sa.Column('shipping_method', sa.String(length=12), nullable=True, comment='发货方式'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='商品表'
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('plant_disease',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plant_id', 'disease_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_disease')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_table('store')
    op.drop_table('category')
    # ### end Alembic commands ###
